.PHONY: clean All

All:
	@echo "----------Building project:[ oled2 - Debug ]----------"
	@"$(MAKE)" -f  "oled2.mk" && "$(MAKE)" -f  "oled2.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ oled2 - Debug ]----------"
	@"$(MAKE)" -f  "oled2.mk" clean
